# -*- coding: utf-8 -*-
"""Image_Classification_CNN_in_cifar10_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dc_ZBTcDonolraKm1OtCgb7kMJMwODiT
"""

import tensorflow as tf
from tensorflow.keras import datasets,layers,models
import matplotlib.pyplot as plt

(x_train,y_train),(x_test,y_test) = datasets.cifar10.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

x_train.shape

x_test.shape

class_names = ['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']

plt.imshow(x_train[7])
plt.show()
class_names[y_train[7][0]]

model = models.Sequential()
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape = (32,32,3)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))

model.summary()

model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10))

model.summary()

model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])

history = model.fit(x_train, y_train, validation_split=0.1, epochs=20)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['training data', 'validation data'], loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['training data', 'validation data'], loc = 'upper right')

import numpy as np
y_pred = model.predict(x_test)

pred=np.argmax(y_pred,axis=1)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

plt.imshow(x_test[2004])
class_names[y_test[2004][0]]

tf.keras.models.save_model(model, 'model.hdf5')

plt.imshow(x_test[2004],cmap='gray')
plt.title(f"y_test:{y_test[2004]},y_pred:{y_pred[2004]}")

